//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_development_project_U2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int id { get; set; }
        public int usuario_id { get; set; }
        public int libro_id { get; set; }
        public System.DateTime fecha_prestamo { get; set; }
        public Nullable<System.DateTime> fecha_devolucion { get; set; }
    
        public virtual Libros Libros { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
